// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebLibrary;

namespace WebLibrary.Migrations
{
    [DbContext(typeof(EFDbcontext))]
    partial class EFDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebLibrary.Webentity", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("brithdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("exceptedsalary")
                        .HasColumnType("bigint");

                    b.Property<long>("experience")
                        .HasColumnType("bigint");

                    b.HasKey("name");

                    b.ToTable("Webpage");
                });
#pragma warning restore 612, 618
        }
    }
}
